---
- name: Explore variables
  hosts: dbserver
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: Print some facts
      tags: IP
      ansible.builtin.debug:
        msg: "{{ ansible_facts['enp0s9']['ipv4']['address'] }}"
    - name: Collect IP
      tags: IP 
      set_fact: 
        ip_private: "{{ ansible_facts['enp0s9']['ipv4']['address'] }}"
    - name: Print custom fact
      tags: IP
      ansible.builtin.debug:
        # TODO: print fact
        msg: "{{ ansible_facts['ip_private'] }}"
      