---
- name: Play 1 prepare file system
  hosts: myservers
  become: yes
  tasks:
    - name: Create Directory
      ansible.builtin.file:
        path: /opt/dummy
        state: directory
        owner: installer
        group: installer
        mode: 0750
