---
- name: Install App
  hosts: appservers
  become: yes
  tags: APP
  tasks:
    - name: Begin Install App
      ansible.builtin.debug:
        msg: "Begin Install app on {{ ansible_hostname }}"
    - name: create user interactif
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /usr/bin/bash
    - name: create group service
      ansible.builtin.group:
        name: "{{ userservicename }}"
        gid: 998
    - name: create user service
      ansible.builtin.user:
        name: "{{ userservicename }}"
        group: "{{ userservicename }}"
        uid: 998
        shell: /usr/sbin/nologin
    - name: Install nginx server + jre Java
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - nginx
        - openjdk-{{ javaversion }}-jre
    - name: nginx service stopped and disabled
      ansible.builtin.systemd:
        name: nginx
        state: stopped
        enabled: false
    - name: copy api artifact
      tags: ARTIFACT
      ansible.builtin.copy:
        src: ~/artifacts/movieapi-{{ javaversion }}.jar
        dest: /opt
        owner: "{{ userservicename }}"
        group: "{{ userservicename }}"
        mode: 0755 
    
    # deploy artifact: movieapi-[java version].jar

- name: Install Db
  hosts: dbserver
  become: yes
  tags: DB
  tasks:
    - name: Begin Install db
      ansible.builtin.debug:
        msg: "Begin Install db on {{ ansible_hostname }}"
    - name: add key repo postgresql
      ansible.builtin.apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present
    - name: add repo postgresql
      ansible.builtin.apt_repository:
        repo: "deb https://apt.postgresql.org/pub/repos/apt  {{ ansible_distribution_release }}-pgdg main"
        state: present

    - name: install postgresql server
      ansible.builtin.apt:
        name: postgresql-{{ postgresqlversion }}
        update_cache: yes